spring:
  sql.init.mode: always # Loading Initialization Data
  
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 114514
  
  jpa:
    hibernate:
      ddl-auto: ${CL_DDL_AUTO}
    show-sql: true
    defer-datasource-initialization: true # Loading Initialization Data

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      location: /app/files
  security:

# Swagger UI Description
apiTitle: "CaptionLive! API"
apiDescription: "A Project Management System for Fansub Groups, developed by Aguri's GRavity Lab. Please see the GitHub page for more information at https://github.com/lijiaxi2018/CaptionLive"
apiVersion: "0.1"

# application.properties
jwt:
  secret: your-secret-key
  expiration: 86400
