spring:
  sql.init.mode: always # Loading Initialization Data
  
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 114514
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true # Loading Initialization Data

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: /app/files
  security:

# Swagger UI Description
apiTitle: "CaptionLive! API"
apiDescription: "A Project Management System for Fansub Groups, developed by Aguri's GRavity Lab. Please see the GitHub page for more information at https://github.com/lijiaxi2018/CaptionLive"
apiVersion: "0.1"

# application.properties
jwt:
  secret: your-secret-key # Sensitive information, need to discuss when go-live
  expiration: 86400

aws:
  s3:
    bucket-name: test-captionlive
    region: us-east-1
  accessKey: 
  secretKey: 