# docker-compose -f docker-compose-dev.yml up --build
version: "3.7"
name: captionlive

services:
  db:
    image: postgres:14.7
    volumes:
      - "../docker-data/psql-data:/var/lib/postgresql/data"
    container_name: captionlive_db_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=114514
  api:
    build:
      context: ../api
      dockerfile: production.DockerFile
    restart: unless-stopped
    depends_on:
      - db
    container_name: captionlive_api_dev
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: ../frontend
      dockerfile: DockerFile
    container_name: captionlive_frontend_dev
    ports:
      - "80:80"