name: Push API Production Image to DockerHub

on:
  push:
    branches: [ "production" ]

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build API Image
        working-directory: ./api
        run: |
          docker build --no-cache -t cl_api_prod -f production.DockerFile .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push to DockerHub
        working-directory: ./api
        run: |
          docker tag cl_api_prod lijiaxi2018/cl_api_prod
          docker push lijiaxi2018/cl_api_prod
      
